### ISSUE TITLE
Failed to load nodelet

### ISSUE THREAD

**Issue by Mitchell-Hampton** [SteveMacenski/ros-realsense-d400-snap-pkg#1]
When I try to run the snap I get the error below.

[FATAL] [1531796355.206003159]: Failed to load nodelet '/camera/realsense2_camera` of type `realsense2_camera/RealSenseNodeFactory` to manager `realsense2_camera_manager'
[camera/realsense2_camera_manager-2] process has died [pid 842, exit code -4, cmd /snap/ros-realsense-d400/1/opt/ros/kinetic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/root/snap/ros-realsense-d400/1/ros/log/62dc0d00-896d-11e8-b583-78d00424ecd9/camera-realsense2_camera_manager-2.log].
log file: /root/snap/ros-realsense-d400/1/ros/log/62dc0d00-896d-11e8-b583-78d00424ecd9/camera-realsense2_camera_manager-2*.log
[camera/realsense2_camera-3] process has died [pid 843, exit code 255, cmd /snap/ros-realsense-d400/1/opt/ros/kinetic/lib/nodelet/nodelet load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=/root/snap/ros-realsense-d400/1/ros/log/62dc0d00-896d-11e8-b583-78d00424ecd9/camera-realsense2_camera-3.log].
log file: /root/snap/ros-realsense-d400/1/ros/log/62dc0d00-896d-11e8-b583-78d00424ecd9/camera-realsense2_camera-3*.log

**Comment by Mitchell-Hampton** [comment]
I tried this on a different PC and it works well. 

It seems it will just not run on the PC I actually want it for...
I can run the rs_rgbd.launch from my catkin workspace fine. I don't see how it then doesn't work from the snap.

**Comment by SteveMacenski** [comment]
Seems like its been solved.

**Comment by Mitchell-Hampton** [comment]
Kind of, it looks like it is limited to only one PC. Do you have any idea what would have caused it?

**Comment by SteveMacenski** [comment]
I would have to know more about your setups.

**Comment by Mitchell-Hampton** [comment]
The PC which it fails on is running Ubuntu 16.04 and has gone though the exact same setup as the other PC. It has a lower spec processor but runs the camera fine when I run it from my workspace. I don't really know where the discrepancies are coming from.

**Comment by SteveMacenski** [comment]
The error you listed is the incredibly generic one, if there wasnt any warnings or error beforehand and I don't know the context of your use, I can't do anything to help.
